### ISSUE TITLE
form

### ISSUE THREAD

**Issue by zkgz** [zkgz/kkn_ppm#5]
Longitude, Latitude luas tanah, luas bangunan di form dapat berupa teks, perlu dirubah agar menerima angka saja

**Comment by deovaliandro** [comment]
sudah selesai....

**Comment by zkgz** [comment]
luas bangunan dan luas tanah masih belum selesai

**Comment by zkgz** [comment]
jika latitude atau longitude diisi oleh teks, outlet map tidak akan muncul di peta

**Comment by zkgz** [comment]
fixed
